`timescale 1ns/1ps

// Read inputs and expected results generated by golden_model.py to check each module.
module tb_hw1;
    localparam integer Q = 3329;

    // Inputs and outputs for the arithmetic units and butterfly.
    reg [11:0] a, b;
    wire [11:0] add_c, sub_c, mul_c;
    reg [11:0] u, v, zeta;
    wire [11:0] uo, vo;
    // Keep the expected results in separate signals so they can also be compared in the waveform.
    reg [11:0] exp_add, exp_sub, exp_mul, exp_uo, exp_vo;
    reg passed;
    reg phase;  // 0: addition, subtraction, and multiplication checks / 1: butterfly checks

    // kind is 0 for provided examples, 1 for corner cases, and 2 for random inputs.
    integer case_id, kind;
    integer arith_count, bfly_count;
    integer add_err, sub_err, mul_err, bfly_err;
    integer arith_total, arith_provided, arith_corner, arith_random;
    integer bfly_total, bfly_provided, bfly_corner, bfly_random;
    // File handles for the input vectors, result CSV, and summary file.
    integer fd, out_fd, summary_fd;
    integer unused;
    reg [1023:0] arith_vec, bfly_vec;
    reg [1023:0] arith_csv, bfly_csv, summary_file;

    // Use the same a and b to check all three arithmetic units at once.
    mod_add dut_add (.a(a), .b(b), .c(add_c));
    mod_sub dut_sub (.a(a), .b(b), .c(sub_c));
    mod_mul dut_mul (.a(a), .b(b), .c(mul_c));
    bfly_ct dut_bfly (.u(u), .v(v), .zeta(zeta), .uo(uo), .vo(vo));

    // Close any open files and stop if a file cannot be opened or the input format is invalid.
    task stop_test;
        input [1023:0] message;
        begin
            $display("INPUT ERROR: %0s (case_id=%0d)", message, case_id);
            if (fd != 0) $fclose(fd);
            if (out_fd != 0) $fclose(out_fd);
            if (summary_fd != 0) $fclose(summary_fd);
            $finish;
        end
    endtask

    // Compare addition, subtraction, and multiplication results with the expected values and log them to CSV.
    task check_arith;
        integer i, n, extra;
        integer ai, bi, ea, es, em;
        integer ok_add, ok_sub, ok_mul;
        integer groups [0:2];
        begin
            fd = $fopen(arith_vec, "r");
            out_fd = $fopen(arith_csv, "w");
            if (fd == 0 || out_fd == 0) stop_test("Cannot open arithmetic input/output file");
            // The first line contains the total count and the counts of provided, corner, and random cases.
            n = $fscanf(fd, "%d %d %d %d", arith_total, arith_provided,
                        arith_corner, arith_random);
            if (n != 4 || arith_provided != 6 || arith_corner < 20 ||
                arith_random < 0 || arith_total != arith_provided + arith_corner + arith_random)
                stop_test("Invalid arithmetic vector header");
            for (i = 0; i < 3; i = i + 1) groups[i] = 0;
            $fdisplay(out_fd, "case_id,kind,time_ns,a,b,expected_add,actual_add,add_ok,expected_sub,actual_sub,sub_ok,expected_mul,actual_mul,mul_ok");

            for (i = 0; i < arith_total; i = i + 1) begin
                // Read one row at a time and check the case number, category, and value ranges.
                n = $fscanf(fd, "%d %d %d %d %d %d %d", case_id, kind, ai, bi, ea, es, em);
                if (n != 7 || case_id != i + 1 || kind < 0 || kind > 2)
                    stop_test("Missing or malformed arithmetic vector");
                if (ai < 0 || ai >= Q || bi < 0 || bi >= Q ||
                    ea < 0 || ea >= Q || es < 0 || es >= Q || em < 0 || em >= Q)
                    stop_test("Arithmetic input/expected result outside 0..3328");
                groups[kind] = groups[kind] + 1;
                a = ai;
                b = bi;
                exp_add = ea;
                exp_sub = es;
                exp_mul = em;
                // Wait 10 ns after changing the inputs so the combinational outputs can settle.
                #10;

                // Use === so outputs containing X or Z do not pass the comparison.
                ok_add = (add_c === exp_add) && (add_c < Q);
                ok_sub = (sub_c === exp_sub) && (sub_c < Q);
                ok_mul = (mul_c === exp_mul) && (mul_c < Q);
                if (!ok_add) add_err = add_err + 1;
                if (!ok_sub) sub_err = sub_err + 1;
                if (!ok_mul) mul_err = mul_err + 1;
                arith_count = arith_count + 1;
                $fdisplay(out_fd, "%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d",
                          case_id, kind, $time, a, b, exp_add, add_c, ok_add,
                          exp_sub, sub_c, ok_sub, exp_mul, mul_c, ok_mul);
                if (!ok_add || !ok_sub || !ok_mul)
                    $display("FAIL arithmetic id=%0d a=%0d b=%0d add=%0d/%0d sub=%0d/%0d mul=%0d/%0d (actual/expected)",
                             case_id, a, b, add_c, exp_add, sub_c, exp_sub, mul_c, exp_mul);
            end

            // After reading the declared rows, check for leftover data and verify the category counts.
            n = $fscanf(fd, "%d", extra);
            if (n != -1) stop_test("Extra or malformed arithmetic data after declared rows");
            if (groups[0] != arith_provided || groups[1] != arith_corner || groups[2] != arith_random)
                stop_test("Arithmetic category counts disagree with header");
            $fclose(fd);
            $fclose(out_fd);
            fd = 0;
            out_fd = 0;
        end
    endtask

    // The butterfly passes only when both uo and vo match the expected results.
    task check_bfly;
        integer i, n, extra;
        integer ui, vi, zi, eu, ev;
        integer ok;
        integer groups [0:2];
        begin
            fd = $fopen(bfly_vec, "r");
            out_fd = $fopen(bfly_csv, "w");
            if (fd == 0 || out_fd == 0) stop_test("Cannot open butterfly input/output file");
            // Check the case counts in the first line, just as for the arithmetic input file.
            n = $fscanf(fd, "%d %d %d %d", bfly_total, bfly_provided,
                        bfly_corner, bfly_random);
            if (n != 4 || bfly_provided != 5 || bfly_corner < 20 ||
                bfly_random < 0 || bfly_total != bfly_provided + bfly_corner + bfly_random)
                stop_test("Invalid butterfly vector header");
            for (i = 0; i < 3; i = i + 1) groups[i] = 0;
            $fdisplay(out_fd, "case_id,kind,time_ns,u,v,zeta,expected_uo,actual_uo,expected_vo,actual_vo,ok");

            for (i = 0; i < bfly_total; i = i + 1) begin
                // Read u, v, zeta, and the expected values for both outputs.
                n = $fscanf(fd, "%d %d %d %d %d %d %d", case_id, kind, ui, vi, zi, eu, ev);
                if (n != 7 || case_id != i + 1 || kind < 0 || kind > 2)
                    stop_test("Missing or malformed butterfly vector");
                if (ui < 0 || ui >= Q || vi < 0 || vi >= Q || zi < 0 || zi >= Q ||
                    eu < 0 || eu >= Q || ev < 0 || ev >= Q)
                    stop_test("Butterfly input/expected result outside 0..3328");
                groups[kind] = groups[kind] + 1;
                u = ui;
                v = vi;
                zeta = zi;
                exp_uo = eu;
                exp_vo = ev;
                // Leave 10 ns between inputs, as in the arithmetic checks.
                #10;

                ok = (uo === exp_uo) && (vo === exp_vo) && (uo < Q) && (vo < Q);
                if (!ok) bfly_err = bfly_err + 1;
                bfly_count = bfly_count + 1;
                $fdisplay(out_fd, "%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d,%0d",
                          case_id, kind, $time, u, v, zeta, exp_uo, uo, exp_vo, vo, ok);
                if (!ok)
                    $display("FAIL butterfly id=%0d u=%0d v=%0d zeta=%0d uo=%0d/%0d vo=%0d/%0d (actual/expected)",
                             case_id, u, v, zeta, uo, exp_uo, vo, exp_vo);
            end

            n = $fscanf(fd, "%d", extra);
            if (n != -1) stop_test("Extra or malformed butterfly data after declared rows");
            if (groups[0] != bfly_provided || groups[1] != bfly_corner || groups[2] != bfly_random)
                stop_test("Butterfly category counts disagree with header");
            $fclose(fd);
            $fclose(out_fd);
            fd = 0;
            out_fd = 0;
        end
    endtask

    initial begin
        // Initialize the inputs, expected results, and counters before starting the checks.
        passed = 0;
        phase = 0;
        case_id = 0;
        kind = 0;
        arith_count = 0;
        bfly_count = 0;
        add_err = 0;
        sub_err = 0;
        mul_err = 0;
        bfly_err = 0;
        fd = 0;
        out_fd = 0;
        summary_fd = 0;
        a = 0;
        b = 0;
        u = 0;
        v = 0;
        zeta = 2580;
        exp_add = 0;
        exp_sub = 0;
        exp_mul = 0;
        exp_uo = 0;
        exp_vo = 0;

        // Use these default files unless paths are supplied at runtime.
        arith_vec = "vectors/mod_arith.txt";
        bfly_vec = "vectors/bfly_ct.txt";
        arith_csv = "sim_results/mod_arith_results.csv";
        bfly_csv = "sim_results/bfly_ct_results.csv";
        summary_file = "sim_results/summary.txt";
        // Arguments such as +ARITH_VEC=path override the corresponding file paths.
        unused = $value$plusargs("ARITH_VEC=%s", arith_vec);
        unused = $value$plusargs("BFLY_VEC=%s", bfly_vec);
        unused = $value$plusargs("ARITH_CSV=%s", arith_csv);
        unused = $value$plusargs("BFLY_CSV=%s", bfly_csv);
        unused = $value$plusargs("SUMMARY=%s", summary_file);

        // Check the arithmetic units first, then change phase and check the butterfly.
        check_arith;
        phase = 1;
        check_bfly;

        // Write the number of cases and errors for each module to the summary file.
        summary_fd = $fopen(summary_file, "w");
        if (summary_fd == 0) stop_test("Cannot open summary file");
        $fdisplay(summary_fd, "q=3329; butterfly zeta=2580; sample interval=10 ns");
        $fdisplay(summary_fd, "Arithmetic: provided=%0d corner=%0d random=%0d", arith_provided, arith_corner, arith_random);
        $fdisplay(summary_fd, "Butterfly: provided=%0d corner=%0d random=%0d", bfly_provided, bfly_corner, bfly_random);
        $fdisplay(summary_fd, "mod_add: cases=%0d errors=%0d", arith_count, add_err);
        $fdisplay(summary_fd, "mod_sub: cases=%0d errors=%0d", arith_count, sub_err);
        $fdisplay(summary_fd, "mod_mul: cases=%0d errors=%0d", arith_count, mul_err);
        $fdisplay(summary_fd, "bfly_ct: cases=%0d errors=%0d", bfly_count, bfly_err);
        $fclose(summary_fd);
        summary_fd = 0;

        $display("mod_add: cases=%0d errors=%0d", arith_count, add_err);
        $display("mod_sub: cases=%0d errors=%0d", arith_count, sub_err);
        $display("mod_mul: cases=%0d errors=%0d", arith_count, mul_err);
        $display("bfly_ct: cases=%0d errors=%0d", bfly_count, bfly_err);
        // The full test passes only if all four modules have zero errors.
        passed = (add_err == 0 && sub_err == 0 && mul_err == 0 && bfly_err == 0);
        if (passed) $display("PASS: all four HW1 modules match the Python golden model.");
        else $display("FAIL: one or more HW1 modules disagree with the Python golden model.");
        $finish;
    end
endmodule
